saveconfig: fix missing import
$ targetcli /backstores/user:glfs/test saveconfig
NameError: "global name 'errno' is not defined"

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>