Fix issue with Path(...).open: needs parenthesis
There are places where the code does this pattern:

   with Path(some_path).open as f:
       ... (do stuff)

But that generates an error message like:

    /> restoreconfig temp.json
    Traceback (most recent call last):
      File "/usr/bin/targetcli", line 8, in <module>
	sys.exit(main())
		 ~~~~^^
      File "/usr/lib/python3.13/site-packages/targetcli/targetcli_shell.py", line 313, in main
	shell.run_interactive()
	~~~~~~~~~~~~~~~~~~~~~^^
      File "/usr/lib/python3.13/site-packages/configshell/shell.py", line 899, in run_interactive
	self._cli_loop()
	~~~~~~~~~~~~~~^^
      File "/usr/lib/python3.13/site-packages/configshell/shell.py", line 728, in _cli_loop
	self.run_cmdline(cmdline)
	~~~~~~~~~~~~~~~~^^^^^^^^^
      File "/usr/lib/python3.13/site-packages/configshell/shell.py", line 842, in run_cmdline
	self._execute_command(path, command, pparams, kparams)
	~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.13/site-packages/configshell/shell.py", line 817, in _execute_command
	result = target.execute_command(command, pparams, kparams)
      File "/usr/lib/python3.13/site-packages/configshell/node.py", line 1405, in execute_command
	return method(*pparams, **kparams)
      File "/usr/lib/python3.13/site-packages/targetcli/ui_root.py", line 207, in ui_command_restoreconfig
	errors = self.rtsroot.restore_from_file(savefile, clear_existing,
						target, storage_object)
      File "/usr/lib/python3.13/site-packages/rtslib/root.py", line 490, in restore_from_file
	with Path(restore_file).open as f:
	     ^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: 'method' object does not support the context manager protocol

Adding empty parenthesis after the "open" fixes the issue.