fix MappedLun typo
Introduced in c37a00b93bff4d89b28992e7c4e6d1fa98351b74,
which is in fb38 and fb39.

The reported error was
NameError: global name 'MappedLun' is not defined.

Signed-off-by: Johannes Dewender <github@JonnyJD.net>