For partitions, retrieve the logical block size of the parent device
Partitions have a sysfs "size" but no "logical_block_size".
As a consequence, we need to look at the parent device to
determine the physical block size of a partition.

This patch fixes an exception raised in `targetcli` when
partitions are listed under /backstores/block:

  FileNotFoundError: [Errno 2] No such file or directory:
  '/sys/block/sdb/sdb1/queue/logical_block_size'

Signed-off-by: Christophe Vu-Brugier <cvubrugier@yahoo.fr>