targetctl: Fix clear command dispatch
Fix a regression introduced by 76e5415a:

Traceback (most recent call last):
  File "targetctl", line 9, in <module>
    sys.exit(main())
             ~~~~^^
  File "rtslib/targetctl.py", line 79, in main
    funcs[sys.argv[1]](savefile)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: clear() takes 0 positional arguments but 1 was given