Depend on pyudev during runtime
In v2.1.fb60 an unconditional dependency to pyudev was added,
which needs to be specified in the egg info, otherwise pip install might fail with e.g.

File "local/lib/python2.7/site-packages/rtslib/utils.py", line 30, in <module>
     import pyudev
 ImportError: No module named pyudev